//! Typed table row definitions and enum-safe categorical types.
//!
//! Represent DomainWall and GaugeCoupling as typed enum-safe values.
//! Use strongly typed SpacetimeDB table rows.
//! Do NOT assume PostgreSQL JSONB syntax/semantics.

use spacetimedb::{table, ReducerContext, Identity, Timestamp};
use serde::{Serialize, Deserialize};

/// DomainWall: three-state connection variable.
/// Categorical type. Never flatten to scalar with assumed ordering.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DomainWall {
    Linked,
    Broken,
    Gradient,
}

/// GaugeCoupling: three-state rotation variable.
/// Categorical type. Never flatten to scalar with assumed ordering.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GaugeCoupling {
    Static,
    Spinning,
    Oscillating,
}

/// Validation outcome for a persisted state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ValidationOutcome {
    Accepted,
    Rerouted,
    Abstained,
    Rejected,
}

/// Source type / provenance of a state event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceType {
    /// Observed from a real recording.
    Observed,
    /// Generated by an LLM.
    Generated,
    /// Predicted by JEPA.
    Predicted,
    /// Synthetic test fixture.
    Synthetic,
    /// Replayed from a trace.
    Replayed,
}

/// Disposition of a generation result.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GenerationStatus {
    Accepted,
    Rerouted,
    Abstained,
    Rejected,
}


/// Codec schema version for persisted Vector15D payloads.
///
/// Old 13-field JSON remains readable: `magnetic_north` / `magnetic_south` default to 0.0.
/// Fields 14–15 are universal polar pre-stress anchors for all shells (not seat-owned).
/// Anaseos ivory-blue is colour/spectrum only.
pub const CODEC_SCHEMA_VERSION: &str = "v15d";
